### ISSUE TITLE
如何将GMBL翻译成ConsCDL和Caption呢？

### ISSUE THREAD

**Issue by iKitsch** [zezeze97/DFE-GPS#1]
您好！对于文献中“Each template is translated into the formal language, ConsCDL, accompanied by detailed natural language captions specifying the shapes and their geometric elements.”这一段内容，请问您是通过什么方法去翻译的呢？是人工翻译、自动化工具，亦或是其它方法？

**Comment by chengruogu0915** [comment]
Hello! This process was carried out by human experts for the translation.

**Comment by chenQ1114** [comment]
您好！请问开源了ImgCDL标注结果文件吗？
formal diagram language representations (ConsCDL and ImgCDL) produced by the Diagram Formalizer.
